### ISSUE TITLE
Crash because of provider.

### ISSUE THREAD

**Issue by IgorGanapolsky** [kmdupr33/PhilHackerNews#1]
Hello,
when I try to run your app, I get an exception:

> com.philosophicalhacker.philhackernews E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                                         Process: com.philosophicalhacker.philhackernews, PID: 19719
>                                                                                         java.lang.RuntimeException: Unable to get provider com.philosophicalhacker.philhackernews.data.cache.HackerNewsContentProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object dagger.ObjectGraph.inject(java.lang.Object)' on a null object reference
>                                                                                             at android.app.ActivityThread.installProvider(ActivityThread.java:5156)
>                                                                                             at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
>                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
>                                                                                             at android.app.ActivityThread.-wrap1(ActivityThread.java)
>                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
>                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                             at android.os.Looper.loop(Looper.java:148)
>                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object dagger.ObjectGraph.inject(java.lang.Object)' on a null object reference
>                                                                                             at com.philosophicalhacker.philhackernews.data.cache.HackerNewsContentProvider.onCreate(HackerNewsContentProvider.java:24)
>                                                                                             at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
>                                                                                             at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
>                                                                                             at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
>                                                                                             at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748) 
>                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688) 
>                                                                                             at android.app.ActivityThread.-wrap1(ActivityThread.java) 
>                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
>                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                             at android.os.Looper.loop(Looper.java:148) 
>                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
>                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

Please advise.

**Comment by kmdupr33** [comment]
Igor,

Sorry I haven't responded to your inquiries and PRs. My life is a bit
chaotic right now, as my wife and I have just decided to move to NYC in the
next few weeks and I'm juggling work with a contract position. I will have
time to respond once things calm down in a few weeks.

Thanks for your patience.

-Matt

**Comment by IgorGanapolsky** [comment]
Awesome, good luck in NYC.  I've lived in this area my whole life.
